In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Artificial Neural Network

### Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.4.1'

## Data Preprocessing

### Importing the dataset

In [4]:
# insert your path
dataset = pd.read_excel('/Folds5x2_pp.xlsx')

In [5]:
# set of independent variables, a matrix of features
X = dataset.iloc[:, :-1].values
print(f'X has {X.shape[0]} rows and {X.shape[1]} columns.')
print()
print(X[:5])

X has 9568 rows and 4 columns.

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 [  20.86   57.32 1010.24   76.64]
 [  10.82   37.5  1009.23   96.62]]


In [6]:
# set of dependent variable, one specific column/vector
y = dataset.iloc[:, -1].values
print(f'y has {y.shape[0]} elements.')
print(y[:5])

y has 9568 elements.
[463.26 444.37 488.56 446.48 473.9 ]


### Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size = 0.2, 
                                                    random_state = 0
                                                    )

print(f'X_train has {X_train.shape[0]} rows and {X_train.shape[1]} columns.')
print(f'X_test has {X_test.shape[0]} rows and {X_test.shape[1]} columns.')
print()
print(f'y_train has {y_train.shape[0]} elements.')
print(f'y_test has {y_test.shape[0]} elements.')

X_train has 7654 rows and 4 columns.
X_test has 1914 rows and 4 columns.

y_train has 7654 elements.
y_test has 1914 elements.


## Building the ANN

### Initializing the ANN as a sequence of layers

In [8]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [9]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [11]:
# usually we do not neet an activation function on the output layer for Regression
ann.add(tf.keras.layers.Dense(units=1))

## Training the ANN

### Compiling the ANN

In [12]:
# for Regression, use MSE 
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [13]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 1s 2ms/step - loss: 363.2338
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 68.6842
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 35.2396
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 29.9616
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 30.5190
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 28.2658
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 27.4835
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 26.8521
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 27.1114
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 28.7006
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 26.2777
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - loss: 26.0478


### Predicting the results of the Test set

In [14]:
y_pred = ann.predict(X_test)
print(f'y_pred has {y_pred.shape[0]} elements.')
print(y_pred[:5])

y_pred has 1914 elements.
[[433.23196]
 [460.95593]
 [466.39465]
 [446.89423]
 [456.96616]]


Compare predicted results with the real results:
- y_test: vector of real results (ground truth)
- y_pred: vector of prediction

In [15]:
# printing options for numpy objects
np.set_printoptions(precision=2)

# convert the horizontal vectors to vertical, with "reshape", and then concatenate them on the vertical axis.
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[433.23 431.23]
 [460.96 460.01]
 [466.39 461.14]
 ...
 [473.04 473.26]
 [439.64 438.  ]
 [458.42 463.28]]
